name: "CI"
on: [push, workflow_dispatch]
env:
  PYTHON_VERSION: "3.13"
jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: setup
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run ruff check
        shell: bash
        run: uv run ruff check .
      - name: Run ruff format check
        shell: bash
        run: uv run ruff format --check .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: setup
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run mypy
        shell: bash
        run: uv run mypy .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - id: setup
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run tests
        shell: bash
        run: uv run pytest .
