name: "CI"
on: [push, pull_request]
env:
  PYTHON_VERSION: 3.8
  POETRY_VERSION: 1.5.1
jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: psf/black@stable
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: cache-deps
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${PYTHON_VERSION}
          poetry-version: ${POETRY_VERSION}
      - name: Run tests
        run: |
          poetry shell pytest .
